---
title: "Analysis on Inflation"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
params:
  portfolio: "sample.csv"
---
# Background
This project aims to answer how inflation is tied to an economy and the economic growth, and how one may combat inflation.

We currently live in a special time in history. While we are still dealing with an ongoing global pandemic,
the economy is also faced with high inflation. High inflation often leads to higher cost of living and decreased
living standard. The goal of this project is to analyze the effect of inflation on the economy. 
In the first part (midterm project), we will examine past inflation data and various economic metrics; this includes but not limited to inflation's effect on cost of living and different assets. 

# Questions of Interest
The main question we aim to answer are the following

1. How does inflation affect the overall economy and economic growth (e.g. GDP)?
2. How does inflation affect the standard of living i.e. CPI?
3. How are different assets affected by inflation (e.g. real estate, stocks)
4. How can one protect themselves from inflation by constructing a portfolio of assets?
   This looks at broader market in terms of different industrial sectors


# Data Source
### Economic Data
The first set of data are important economic metrics and indicators.
The data is extracted from [World Bank](https://data.worldbank.org/indicator). The following indicators are used:

1. GDP (Current US $)
2. GDP growth (annual %)
3. Inflation (annual %)
4. Inflation, consumer prices (annual %)

Another source of data is from Organisation for Economic Co-operation and Development ([OECD](https://www.oecd.org/)).
Data from OECD includes

1. Inflation
2. Housing Prices
3. Shares Prices

### Stock Price Data
Stock data are mainly extracted from [Alpha Vantage](https://www.alphavantage.co/) and [Finnhub](https://finnhub.io/).

The API for Alpha Vantage and Finnhub are only availble in Python and other non-R languages, and therefore the data is extracted
in the code [here](https://hgeorge21.github.io/JSC370-finalproject/data_download.py)


# Tools Used
Overall, the main tools used for the project are R and Python.

Python is focused towards data collection from Finnhub and Alpha Vantage for
market and some economics data focused in the US. Note that an alternative option
to storing the data for time series, especially stocks prices, is the use of K-database ([`KDB`](https://code.kx.com/q/))
with the use of `q` language. However, this adds to the complexity of the project
with the installation requirement, license and etc.; it is thus not used.

R is used for the analytics, data cleaning, and constructing interactive plots

* `tidylr` for piping
* `dplyr` for table manipulations
* `data.tables` for more table manipulations
* `ggplot` and `plotly` for visualization


# PDF Report Download
Click [here](https://hgeorge21.github.io/JSC370-finalproject/noreportError.html) to download report




