---
title: "Analysis on Inflation"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

```{r setup, message=F, warning=F, include=F}
# setup
library(stringr)
library(ggplot2)
library(dplyr)
library(data.table)
library(plotly)
```

# Overview
*DISCLAIMER: This page does not imply any investment advice of opinion in any shape or form*

Here, we will examine the performance of different asset classes and
how they correlate with inflation. The main ones we will focus on are

* Equities and ETFs (different sectors)
* Housing prices

<br>

# U.S. Equity Market
```{r loadetf_map, echo=F}
etfs <- data.table::fread('./data/etfs.csv')
knitr::kable(etfs, caption="US Market and Sector Index ETFs")
```

```{r loadprices, echo=F}
symbol_lst <- list.files("./data/prices/")
prices <- c()
for(fsym in symbol_lst) {
  sym <- substr(fsym, 1, str_locate(fsym, ".csv")-1)
  if(sym %in% etfs$ETF) {
    df = read.csv(paste('./data/prices/', fsym, sep=''))
    df['sym'] <- sym
    df <- df[,!names(df) %in% c('X')]
    prices <- rbind(prices, df)
  }
}

# convert date from str
prices$timestamp <- as.Date(prices$timestamp)

# Add first price from each series to perform normalization
first_px <- prices %>%
  group_by(sym) %>%
  summarise(firstPx=last(close)) # note the dataframe is reverse in time
prices <- merge(x=prices, y=first_px, by='sym')

prices['normPx'] <- prices['close'] / prices['firstPx']
```

## Price Charts {.tabset}
### Raw Prices
```{r echo=F}
prices %>%
  filter(sym %in% etfs$ETF) %>%
  ggplot() +
    aes(x=timestamp, y=close, col=sym) +
    geom_line() +
    labs(x='Date', y='Price (USD)') -> etf_raw_plt
ggplotly(etf_raw_plt)
```


### Normalized Prices
```{r echo=F}
etf_px_plt <- ggplot(prices,
                     aes(x=timestamp, y=normPx, colour=sym)) +
              geom_line() +
              labs(x='Date', y='Normalized Price')
ggplotly(etf_px_plt)
```

